#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/ProcessingTest.jar:$APPDIR/lib/resources.jar:$APPDIR/lib/rt.jar:$APPDIR/lib/jsse.jar:$APPDIR/lib/jce.jar:$APPDIR/lib/charsets.jar:$APPDIR/lib/jfr.jar:$APPDIR/lib/access-bridge-64.jar:$APPDIR/lib/cldrdata.jar:$APPDIR/lib/dnsns.jar:$APPDIR/lib/jaccess.jar:$APPDIR/lib/jfxrt.jar:$APPDIR/lib/localedata.jar:$APPDIR/lib/nashorn.jar:$APPDIR/lib/sunec.jar:$APPDIR/lib/sunjce_provider.jar:$APPDIR/lib/sunmscapi.jar:$APPDIR/lib/sunpkcs11.jar:$APPDIR/lib/zipfs.jar:$APPDIR/lib/core.jar:$APPDIR/lib/ttslib.jar:$APPDIR/lib/freetts.jar:$APPDIR/lib/controlP5.jar" ProcessingTest
